---

spring:
  application:
    name: rastibot
  main:
    banner-mode: off
  datasource:
    url: jdbc:postgresql://localhost:5435/rastibot
    username: rastibot
    password: rastibot
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: on
  jpa:
    open-in-view: false
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect
    properties:
      hibernate.temp.use_jdbc_metadata_defaults: false

logging:
  level:
    root: INFO

telegram:
  token: "DO-NOT-COMMIT-KEYS"
  mode: POLLING
  logLevel: Body

rastibot:
  admin-chat-id: 228089372
  birthday-reminder-service:
    schedule:
      enabled: true
      zone: ${BIRTHDAY_REMINDER_SCHEDULE_SERVICE_ZONE:Europe/Sofia}
      batch-size: ${BIRTHDAY_REMINDER_SERVICE_SCHEDULE_BATCH_SIZE:100}
      last-updated-reminder-hours: ${BIRTHDAY_REMINDER_SERVICE_SCHEDULE_LAST_UPDATED_REMINDER_HOURS:6}
      cron: ${BIRTHDAY_REMINDER_SERVICE_SCHEDULE_CRON:0 0 8 * * *}
