---

spring:
  application:
    name: rastibot
  main:
    banner-mode: off

logging:
  config: ${LOGGING_CONFIG}
  level:
    root: INFO

telegram:
  token: ${TELEGRAM_TOKEN}
  mode: ${TELEGRAM_MODE}
  logLevel: none

google-cloud:
  project-id: ${RASTIBOT_GOOGLE_CLOUD_PROJECT_ID}
  pub-sub:
    publish:
      topics:
        - key: check-birthday-reminder-exists
          name: ${RASTIBOT_GOOGLE_CLOUD_PUB_SUB_TOPICS_CHECK_BIRTHDAY_REMINDER_EXISTS}
        - key: create-birthday-reminder
          name: ${RASTIBOT_GOOGLE_CLOUD_PUB_SUB_TOPICS_CREATE_BIRTHDAY_REMINDER}
        - key: birthday-reminder-notification-action
          name: ${RASTIBOT_GOOGLE_CLOUD_PUB_SUB_TOPICS_BIRTHDAY_REMINDER_NOTIFICATION_ACTION}
        - key: list-birthday-reminders
          name: ${RASTIBOT_GOOGLE_CLOUD_PUB_SUB_TOPICS_LIST_BIRTHDAY_REMINDERS}
        - key: delete-birthday-reminder
          name: ${RASTIBOT_GOOGLE_CLOUD_PUB_SUB_TOPICS_DELETE_BIRTHDAY_REMINDER}

    subscribe:
      subscriptions:
        - key: check-birthday-reminder-exists-result
          name: ${RASTIBOT_GOOGLE_CLOUD_PUB_SUB_SUBSCRIPTIONS_CHECK_BIRTHDAY_REMINDER_RESULT}
        - key: create-birthday-reminder-result
          name: ${RASTIBOT_GOOGLE_CLOUD_PUB_SUB_SUBSCRIPTIONS_CREATE_BIRTHDAY_REMINDER_RESULT}
        - key: birthday-reminder-notification
          name: ${RASTIBOT_GOOGLE_CLOUD_PUB_SUB_SUBSCRIPTIONS_BIRTHDAY_REMINDER_NOTIFICATION}
        - key: birthday-reminder-notification-action-result
          name: ${RASTIBOT_GOOGLE_CLOUD_PUB_SUB_SUBSCRIPTIONS_BIRTHDAY_REMINDER_NOTIFICATION_ACTION_RESULT}
        - key: list-birthday-reminders-result
          name: ${RASTIBOT_GOOGLE_CLOUD_PUB_SUB_SUBSCRIPTIONS_LIST_BIRTHDAY_REMINDERS_RESULT}
        - key: delete-birthday-reminder-result
          name: ${RASTIBOT_GOOGLE_CLOUD_PUB_SUB_SUBSCRIPTIONS_DELETE_BIRTHDAY_REMINDER_RESULT}

rastibot:
  admin-chat-id: ${RASTIBOT_ADMIN_CHAT_ID}
  awareness-level: ${RASTIBOT_AWARENESS_LEVEL}
  user-service:
    url: ${RASTIBOT_USER_SERVICE_URL}
  birthday-reminder-service:
    url: ${RASTIBOT_BIRTHDAY_REMINDER_SERVICE_URL}
