- name: Build configuration file
  hosts: local
  connection: local
  tasks:
    - name: "Include vars/all/vars.yml"
      include_vars: "{{ playbook_dir }}/../vars/all/vars.yml"

    - name: "Include vars/all/vault.yml"
      include_vars: "{{ playbook_dir }}/../vars/all/vault.yml"

    - name: "Include vars/{{ env }}/vars.yml"
      include_vars: "{{ playbook_dir }}/../vars/{{ env }}/vars.yml"

    - name: "Include vars/{{ env }}/vault.yml"
      include_vars: "{{ playbook_dir }}/../vars/{{ env }}/vault.yml"

    - name: Check .deploy directory
      stat:
        path: "{{ playbook_dir }}/../../.deploy"
      register: deploy_dir

    - name: "Echo if .deploy directory exists"
      debug:
        msg: ".deploy directory already exists"
      when: deploy_dir.stat.exists

    - name: "Create .deploy directory if does not exist"
      file:
        path: "{{ playbook_dir }}/../../.deploy"
        state: directory
      when: deploy_dir.stat.exists == false

    - name: "Build rastibot-{{ env }}.yml"
      template: src={{ playbook_dir }}/../templates/rastibot-{{ env }}.yml.j2 dest={{ playbook_dir }}/../../.deploy/rastibot-{{ env }}.yml

    - name: "Create application configuration JSON"
      copy: content="{{ application_credentials_config_json }}" dest=~/creds/application-credentials.json

    - name: "Create cloud sql proxy configuration JSON"
      copy: content="{{ cloud_sql_proxy_credentials_config_json }}" dest=~/creds/cloud-sql-proxy-credentials.json

    - name: "Remove previous stack rastibot-{{ env }} if exists"
      command:
        cmd: docker stack rm rastibot-{{ env }}
      ignore_errors: yes

    - name: "Run Docker stack rastibot-{{ env }}"
      command:
        cmd: docker stack deploy --compose-file {{ playbook_dir }}/../../.deploy/rastibot-{{ env }}.yml rastibot-{{ env }}
