---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rastibot
  labels:
    app: rastibot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rastibot
  template:
    metadata:
      labels:
        app: rastibot
    spec:
      containers:
        - name: rastibot
          image: eu.gcr.io/playaround-245909/rastibot:2.0.4
          imagePullPolicy: Always
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "production"
            - name: TELEGRAM_TOKEN
              valueFrom:
                secretKeyRef:
                  name: rastibot
                  key: telegram-token
            - name: TELEGRAM_MODE
              value: polling
            - name: RASTIBOT_ADMIN_CHAT_ID
              valueFrom:
                secretKeyRef:
                  name: rastibot
                  key: admin-chat-id
            - name: RASTIBOT_AWARENESS_LEVEL
              value: "1"
            - name: RASTIBOT_GOOGLE_CLOUD_PROJECT_ID
              value: "playaround-245909"
            - name: RASTIBOT_USER_SERVICE_URL
              value: "rastibot-user-service:9294"
            - name: RASTIBOT_BIRTHDAY_REMINDER_SERVICE_URL
              value: "rastibot-birthday-reminder-service:9292"
            - name: RASTIBOT_GOOGLE_CLOUD_PUB_SUB_TOPICS_CHECK_BIRTHDAY_REMINDER_EXISTS
              value: "prod-check-birthday-reminder-exists"
            - name: RASTIBOT_GOOGLE_CLOUD_PUB_SUB_TOPICS_CREATE_BIRTHDAY_REMINDER
              value: "prod-create-birthday-reminder"
            - name: RASTIBOT_GOOGLE_CLOUD_PUB_SUB_TOPICS_BIRTHDAY_REMINDER_NOTIFICATION_ACTION
              value: "prod-birthday-reminder-notification-action"
            - name: RASTIBOT_GOOGLE_CLOUD_PUB_SUB_SUBSCRIPTIONS_CHECK_BIRTHDAY_REMINDER_RESULT
              value: "prod-check-birthday-reminder-exists-result-subscription"
            - name: RASTIBOT_GOOGLE_CLOUD_PUB_SUB_SUBSCRIPTIONS_CREATE_BIRTHDAY_REMINDER_RESULT
              value: "prod-create-birthday-reminder-result-subscription"
            - name: RASTIBOT_GOOGLE_CLOUD_PUB_SUB_SUBSCRIPTIONS_BIRTHDAY_REMINDER_NOTIFICATION
              value: "prod-birthday-reminder-notification-subscription"
            - name: RASTIBOT_GOOGLE_CLOUD_PUB_SUB_SUBSCRIPTIONS_BIRTHDAY_REMINDER_NOTIFICATION_ACTION_RESULT
              value: "prod-birthday-reminder-notification-action-result-subscription"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rastibot-birthday-reminder-service
  labels:
    app: rastibot-birthday-reminder-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rastibot-birthday-reminder-service
  template:
    metadata:
      labels:
        app: rastibot-birthday-reminder-service
    spec:
      containers:
        - name: rastibot-birthday-reminder-service
          image: eu.gcr.io/playaround-245909/rastibot-birthday-reminder-service:2.0.4
          imagePullPolicy: Always
          ports:
            - containerPort: 9292
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "production"
            - name: DATASOURCE_URL
              value: "127.0.0.1:5432"
            - name: DATASOURCE_DBNAME
              value: "rastibot_birthday_reminder_service"
            - name: DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rastibot
                  key: rastibot-birthday-reminder-service-password
            - name: BIRTHDAY_REMINDER_GOOGLE_CLOUD_PROJECT_ID
              value: "playaround-245909"
            - name: BIRTHDAY_REMINDER_SERVICE_GOOGLE_CLOUD_PUB_SUB_TOPICS_CHECK_BIRTHDAY_REMINDER_EXISTS_RESULT
              value: "prod-check-birthday-reminder-exists-result"
            - name: BIRTHDAY_REMINDER_SERVICE_GOOGLE_CLOUD_PUB_SUB_TOPICS_CREATE_BIRTHDAY_REMINDER_RESULT
              value: "prod-create-birthday-reminder-result"
            - name: BIRTHDAY_REMINDER_SERVICE_GOOGLE_CLOUD_PUB_SUB_TOPICS_BIRTHDAY_REMINDER_NOTIFICATION
              value: "prod-birthday-reminder-notification"
            - name: BIRTHDAY_REMINDER_SERVICE_GOOGLE_CLOUD_PUB_SUB_TOPICS_BIRTHDAY_REMINDER_NOTIFICATION_ACTION_RESULT
              value: "prod-birthday-reminder-notification-action-result"
            - name: BIRTHDAY_REMINDER_SERVICE_GOOGLE_CLOUD_PUB_SUB_SUBSCRIPTIONS_CHECK_BIRTHDAY_REMINDER_EXISTS
              value: "prod-check-birthday-reminder-exists-subscription"
            - name: BIRTHDAY_REMINDER_SERVICE_GOOGLE_CLOUD_PUB_SUB_SUBSCRIPTIONS_CREATE_BIRTHDAY_REMINDER
              value: "prod-create-birthday-reminder-subscription"
            - name: BIRTHDAY_REMINDER_SERVICE_GOOGLE_CLOUD_PUB_SUB_SUBSCRIPTIONS_BIRTHDAY_REMINDER_NOTIFICATION_ACTION
              value: "prod-birthday-reminder-notification-action-subscription"
            - name: BIRTHDAY_REMINDER_SERVICE_SCHEDULE_BATCH_SIZE
              value: "100"
            - name: BIRTHDAY_REMINDER_SERVICE_SCHEDULE_CRON
              value: "0 0 8 * * *"
        - name: cloudsql-proxy
          image: gcr.io/cloudsql-docker/gce-proxy:1.14
          command: ["/cloud_sql_proxy",
                    "-instances=playaround-245909:europe-west4:rastibot=tcp:5432",
                    "-credential_file=/secrets/cloudsql/credentials.json"]
          securityContext:
            runAsUser: 2
            allowPrivilegeEscalation: false
          volumeMounts:
            - name: cloudsql-instance-credentials
              mountPath: /secrets/cloudsql
              readOnly: true
      volumes:
        - name: cloudsql-instance-credentials
          secret:
            secretName: cloudsql-instance-credentials
---
apiVersion: v1
kind: Service
metadata:
  name: rastibot-birthday-reminder-service
  labels:
    app: rastibot-birthday-reminder-service
spec:
  ports:
    - port: 9292
      protocol: TCP
  selector:
    app: rastibot-birthday-reminder-service

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rastibot-user-service
  labels:
    app: rastibot-user-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rastibot-user-service
  template:
    metadata:
      labels:
        app: rastibot-user-service
    spec:
      containers:
        - name: rastibot-user-service
          image: eu.gcr.io/playaround-245909/rastibot-user-service:2.0.2
          imagePullPolicy: Always
          ports:
            - containerPort: 9294
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "production"
            - name: DATASOURCE_URL
              value: "127.0.0.1:5432"
            - name: DATASOURCE_DBNAME
              value: "rastibot_user_service"
            - name: DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rastibot
                  key: rastibot-user-service-password
        - name: cloudsql-proxy
          image: gcr.io/cloudsql-docker/gce-proxy:1.14
          command: ["/cloud_sql_proxy",
                    "-instances=playaround-245909:europe-west4:rastibot=tcp:5432",
                    "-credential_file=/secrets/cloudsql/credentials.json"]
          securityContext:
            runAsUser: 2
            allowPrivilegeEscalation: false
          volumeMounts:
            - name: cloudsql-instance-credentials
              mountPath: /secrets/cloudsql
              readOnly: true
      volumes:
        - name: cloudsql-instance-credentials
          secret:
            secretName: cloudsql-instance-credentials
---
apiVersion: v1
kind: Service
metadata:
  name: rastibot-user-service
  labels:
    app: rastibot-user-service
spec:
  ports:
    - port: 9294
      protocol: TCP
  selector:
    app: rastibot-user-service
