apiVersion: v1
kind: Secret
metadata:
  name: rastibot
type: Opaque
data:
  telegram-token: "TOKEN"
  rastibot-birthday-reminder-service-password: "PASSWORD"
  rastibot-user-service-password: "PASSWORD"
  admin-chat-id: "CHATID"