---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rastibot
  labels:
    app: rastibot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rastibot
  template:
    metadata:
      labels:
        app: rastibot
    spec:
      volumes:
        - name: creds-dir
          hostPath:
            path: /data/rastibot/creds
      containers:
        - name: rastibot
          image: eu.gcr.io/playaround-245909/rastibot:2.0.0
          imagePullPolicy: Always
          terminationMessagePath: "/Users/roman-rastiehaiev-developer/.tmp/rastibot.log"
          volumeMounts:
            - name: creds-dir
              mountPath: /etc/rastibot/creds
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "development"
            - name: TELEGRAM_TOKEN
              value: 869303274:AAGStlaMx75wMfwZSNnnFyhHdScoALsDS2A
            - name: TELEGRAM_MODE
              value: polling
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: "/etc/rastibot/creds/playaround-245909-d902f867f31b.json"
            - name: RASTIBOT_GOOGLE_CLOUD_PROJECT_ID
              value: "playaround-245909"
            - name: RASTIBOT_USER_SERVICE_URL
              value: "rastibot-user-service:9294"
            - name: RASTIBOT_GOOGLE_CLOUD_PUB_SUB_TOPICS_CHECK_BIRTHDAY_REMINDER_EXISTS
              value: "dev-check-birthday-reminder-exists"
            - name: RASTIBOT_GOOGLE_CLOUD_PUB_SUB_TOPICS_CREATE_BIRTHDAY_REMINDER
              value: "dev-create-birthday-reminder"
            - name: RASTIBOT_GOOGLE_CLOUD_PUB_SUB_TOPICS_BIRTHDAY_REMINDER_NOTIFICATION_ACTION
              value: "dev-birthday-reminder-notification-action"
            - name: RASTIBOT_GOOGLE_CLOUD_PUB_SUB_SUBSCRIPTIONS_CHECK_BIRTHDAY_REMINDER_RESULT
              value: "dev-check-birthday-reminder-exists-result-subscription"
            - name: RASTIBOT_GOOGLE_CLOUD_PUB_SUB_SUBSCRIPTIONS_CREATE_BIRTHDAY_REMINDER_RESULT
              value: "dev-create-birthday-reminder-result-subscription"
            - name: RASTIBOT_GOOGLE_CLOUD_PUB_SUB_SUBSCRIPTIONS_BIRTHDAY_REMINDER_NOTIFICATION
              value: "dev-birthday-reminder-notification-subscription"
            - name: RASTIBOT_GOOGLE_CLOUD_PUB_SUB_SUBSCRIPTIONS_BIRTHDAY_REMINDER_NOTIFICATION_ACTION_RESULT
              value: "dev-birthday-reminder-notification-action-result-subscription"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rastibot-birthday-reminder-service
  labels:
    app: rastibot-birthday-reminder-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rastibot-birthday-reminder-service
  template:
    metadata:
      labels:
        app: rastibot-birthday-reminder-service
    spec:
      volumes:
        - name: creds-dir
          hostPath:
            path: /data/rastibot/creds
      containers:
        - name: rastibot-birthday-reminder-service
          image: eu.gcr.io/playaround-245909/rastibot-birthday-reminder-service:2.0.0
          imagePullPolicy: Always
          volumeMounts:
            - name: creds-dir
              mountPath: /etc/rastibot/creds
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "development"
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: "/etc/rastibot/creds/playaround-245909-d902f867f31b.json"
            - name: DATASOURCE_URL
              value: "postgres-birthday-reminder-service:5432"
            - name: DATASOURCE_DBNAME
              value: "rastibot_birthday_reminder_service"
            - name: DATASOURCE_PASSWORD
              value: "birthday_reminder_service_password"
            - name: BIRTHDAY_REMINDER_GOOGLE_CLOUD_PROJECT_ID
              value: "playaround-245909"
            - name: BIRTHDAY_REMINDER_SERVICE_GOOGLE_CLOUD_PUB_SUB_TOPICS_CHECK_BIRTHDAY_REMINDER_EXISTS_RESULT
              value: "dev-check-birthday-reminder-exists-result"
            - name: BIRTHDAY_REMINDER_SERVICE_GOOGLE_CLOUD_PUB_SUB_TOPICS_CREATE_BIRTHDAY_REMINDER_RESULT
              value: "dev-create-birthday-reminder-result"
            - name: BIRTHDAY_REMINDER_SERVICE_GOOGLE_CLOUD_PUB_SUB_TOPICS_BIRTHDAY_REMINDER_NOTIFICATION
              value: "dev-birthday-reminder-notification"
            - name: BIRTHDAY_REMINDER_SERVICE_GOOGLE_CLOUD_PUB_SUB_TOPICS_BIRTHDAY_REMINDER_NOTIFICATION_ACTION_RESULT
              value: "dev-birthday-reminder-notification-action-result"
            - name: BIRTHDAY_REMINDER_SERVICE_GOOGLE_CLOUD_PUB_SUB_SUBSCRIPTIONS_CHECK_BIRTHDAY_REMINDER_EXISTS
              value: "dev-check-birthday-reminder-exists-subscription"
            - name: BIRTHDAY_REMINDER_SERVICE_GOOGLE_CLOUD_PUB_SUB_SUBSCRIPTIONS_CREATE_BIRTHDAY_REMINDER
              value: "dev-create-birthday-reminder-subscription"
            - name: BIRTHDAY_REMINDER_SERVICE_GOOGLE_CLOUD_PUB_SUB_SUBSCRIPTIONS_BIRTHDAY_REMINDER_NOTIFICATION_ACTION
              value: "dev-birthday-reminder-notification-action-subscriber"
            - name: BIRTHDAY_REMINDER_SERVICE_BATCH_SIZE
              value: "100"
            - name: BIRTHDAY_REMINDER_SERVICE_SCHEDULE_CRON
              value: "0 7 * * * *"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rastibot-user-service
  labels:
    app: rastibot-user-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rastibot-user-service
  template:
    metadata:
      labels:
        app: rastibot-user-service
    spec:
      containers:
        - name: rastibot-user-service
          image: eu.gcr.io/playaround-245909/rastibot-user-service:2.0.0
          imagePullPolicy: Always
          ports:
            - containerPort: 9294
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "development"
            - name: DATASOURCE_URL
              value: "postgres-user-service:5432"
            - name: DATASOURCE_DBNAME
              value: "rastibot_user_service"
            - name: DATASOURCE_PASSWORD
              value: "rastibot_user_service_password"
---
apiVersion: v1
kind: Service
metadata:
  name: rastibot-user-service
  labels:
    app: rastibot-user-service
spec:
  ports:
    - port: 9294
      protocol: TCP
  selector:
    app: rastibot-user-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-user-service
  labels:
    app: postgres-user-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-user-service
  template:
    metadata:
      labels:
        app: postgres-user-service
    spec:
      containers:
        - name: postgres-user-service
          image: sameersbn/postgresql:10-2
          ports:
            - containerPort: 5432
          env:
            - name: DB_NAME
              value: "rastibot_user_service"
            - name: DB_USER
              value: "rastibot-user-service"
            - name: DB_PASS
              value: "rastibot_user_service_password"
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-user-service
  labels:
    app: postgres-user-service
spec:
  ports:
    - port: 5433
      protocol: TCP
  selector:
    app: postgres-user-service
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-birthday-reminder-service
  labels:
    app: postgres-birthday-reminder-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-birthday-reminder-service
  template:
    metadata:
      labels:
        app: postgres-birthday-reminder-service
    spec:
      containers:
        - name: postgres-birthday-reminder-service
          image: sameersbn/postgresql:10-2
          ports:
            - containerPort: 5432
          env:
            - name: DB_NAME
              value: "rastibot_birthday_reminder_service"
            - name: DB_USER
              value: "rastibot-birthday-reminder-service"
            - name: DB_PASS
              value: "birthday_reminder_service_password"
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-birthday-reminder-service
  labels:
    app: postgres-birthday-reminder-service
spec:
  ports:
    - port: 5434
      protocol: TCP
  selector:
    app: postgres-birthday-reminder-service
  clusterIP: None
