---
version: '3.1'

services:
  postgres:
    image: sameersbn/postgresql:10-2
    environment:
      DB_NAME: "rastibot"
      DB_USER: "rastibot"
      DB_PASS: "rastibot"
    ports:
      - "5435:5432"
